README.md, graphql/src/main/java/io/jmix/graphql/datafetcher/FilterConditionBuilder.java, graphql/src/main/java/io/jmix/graphql/schema/FilterManager.java, graphql/src/main/java/io/jmix/graphql/schema/FilterManagerImpl.java, graphql/src/main/java/io/jmix/graphql/schema/FilterTypesBuilder.java, graphql/src/main/java/io/jmix/graphql/schema/SchemaBuilder.java, graphql/src/main/java/io/jmix/graphql/schema/Types.java, graphql/src/main/java/io/jmix/graphql/schema/scalar/DateScalar.java, graphql/src/main/java/io/jmix/graphql/schema/scalar/LocalDateTimeScalar.java, graphql/src/test/groovy/FiltrationTest.groovy, graphql/src/test/groovy/scalars/DateScalarTest.groovy, graphql/src/test/groovy/scalars/LocalDateTimeScalarTest.groovy
Fixed bug with void scalar
Test example was added for FilterTypesBuilder
Tests were added for FilterManager
Fix after review
Filter with empty and not values
Grouping filter operations by scalar type
=> Customize filter types for scalar conditions #10

graphql/src/main/java/io/jmix/graphql/datafetcher/EntityMutationDataFetcher.java, graphql/src/main/java/io/jmix/graphql/datafetcher/GqlEntityValidationException.java, graphql/src/test/resources/scripts/security.sql, graphql/src/test/resources/scripts/tables.sql
Permissions check and security scope in tests were added
=> User can delete entity without permission #62

graphql/src/main/java/io/jmix/graphql/datafetcher/DataFetcherPlanBuilder.java
=> User can read forbidden attribute #61

graphql/src/main/java/io/jmix/graphql/datafetcher/EnvironmentUtils.java, graphql/src/main/java/io/jmix/graphql/datafetcher/PermissionDataFetcher.java, graphql/src/main/java/io/jmix/graphql/limitation/GqlBlockedException.java, graphql/src/main/java/io/jmix/graphql/limitation/LimitationProperties.java, graphql/src/main/java/io/jmix/graphql/limitation/OperationRateLimitInstrumentation.java, graphql/src/main/java/io/jmix/graphql/limitation/OperationRateLimitService.java, graphql/src/main/java/io/jmix/graphql/servlet/JmixGraphQLServlet.java, graphql/src/test/groovy/io/jmix/graphql/AbstractGraphQLTest.groovy, graphql/src/test/groovy/io/jmix/graphql/datafetcher/FilterIntegrationTest.groovy, graphql/src/test/groovy/io/jmix/graphql/datafetcher/MutationValidationTest.groovy, graphql/src/test/groovy/io/jmix/graphql/limitation/OperationRateLimitServiceTest.groovy, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/upsert-car.graphql, graphql/src/test/resources/test_support/test-app-limitations.properties
rate limit has been implemented with tests
=> Operation rate limit #39

graphql/src/main/java/io/jmix/graphql/security/SpecificPermissionInstrumentation.java
Check permissions has been disabled for "IntrospectionQuery" operation
=> Introspection query should be allowed for non-authenticated user #91

graphql/src/main/java/io/jmix/graphql/datafetcher/EntityMutationDataFetcher.java, graphql/src/test/groovy/io/jmix/graphql/datafetcher/MutationTest.groovy
Checking of necessary to reload entity has been fixed
=> Mutation: unfetched attribute exception when trying to load back fields which are not in the mutation #20

graphql/src/main/java/io/jmix/graphql/datafetcher/EntityMutationDataFetcher.java, graphql/src/test/groovy/io/jmix/graphql/datafetcher/MutationValidationTest.groovy, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/upsert-datatypes-test-entity.graphql
Validation modifies read-only attributes was implemented
=> Unfetched attribute exception when mutating an entity that contains a read-only field #85

graphql/src/main/java/io/jmix/graphql/schema/NamingUtils.java, graphql/src/test/groovy/io/jmix/graphql/schema/FilterComponentTest.groovy
The naming of input definitions was changed
=> Validation error of type UnknownType for entity list in frontend screen #100

graphql/src/main/java/io/jmix/graphql/datafetcher/EntityMutationDataFetcher.java
Messages of PersistenceException and AccessDeniedException were separated for a bit more details
=> Displaying custom message for bean validation #67

graphql/src/main/java/io/jmix/graphql/datafetcher/EntityMutationDataFetcher.java, graphql/src/main/java/io/jmix/graphql/schema/scalar/BaseDateCoercing.java, graphql/src/main/java/io/jmix/graphql/schema/scalar/DateScalar.java, graphql/src/main/java/io/jmix/graphql/schema/scalar/DateTimeScalar.java, graphql/src/main/java/io/jmix/graphql/schema/scalar/LocalDateScalar.java, graphql/src/main/java/io/jmix/graphql/schema/scalar/LocalDateTimeScalar.java, graphql/src/main/java/io/jmix/graphql/schema/scalar/LocalTimeScalar.java, graphql/src/main/java/io/jmix/graphql/schema/scalar/OffsetDateTimeScalar.java, graphql/src/main/java/io/jmix/graphql/schema/scalar/OffsetTimeScalar.java, graphql/src/main/java/io/jmix/graphql/schema/scalar/TimeScalar.java, graphql/src/test/groovy/io/jmix/graphql/schema/scalars/DateScalarTest.groovy, graphql/src/test/groovy/io/jmix/graphql/schema/scalars/DateTimeScalarTest.groovy, graphql/src/test/groovy/io/jmix/graphql/schema/scalars/LocalDateScalarTest.groovy, graphql/src/test/groovy/io/jmix/graphql/schema/scalars/LocalDateTimeScalarTest.groovy, graphql/src/test/groovy/io/jmix/graphql/schema/scalars/LocalTimeScalarTest.groovy, graphql/src/test/groovy/io/jmix/graphql/schema/scalars/OffsetDateTimeScalarTest.groovy, graphql/src/test/groovy/io/jmix/graphql/schema/scalars/OffsetTimeScalarTest.groovy, graphql/src/test/groovy/io/jmix/graphql/schema/scalars/TimeScalarTest.groovy
Fixed error message when attribute is forbidden by security and when cannot parse string to Date types
=> Error messages when something is forbidden by security #59

graphql/src/test/groovy/io/jmix/graphql/AbstractGraphQLTest.groovy, graphql/src/test/groovy/io/jmix/graphql/datafetcher/MutationTest.groovy, graphql/src/test/groovy/io/jmix/graphql/datafetcher/SecurityTest.groovy, graphql/src/test/groovy/io/jmix/graphql/limitation/OperationRateLimitServiceTest.groovy, graphql/src/test/java/test_support/RestTestUtils.java, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/delete-car.gql, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/delete-garage.gql, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/upsert-car.gql, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/upsert-garage.gql, graphql/src/test/resources/io/jmix/graphql/liquibase/security.sql
Tests for roles access were added
=> Add security to jmix-graphql test project #71

README.md, graphql/src/main/java/io/jmix/graphql/NamingUtils.java, graphql/src/main/java/io/jmix/graphql/accesscontext/GraphqlAccessContext.java, graphql/src/main/java/io/jmix/graphql/datafetcher/PermissionDataFetcher.java, graphql/src/main/java/io/jmix/graphql/schema/PermissionTypesGenerator.java, graphql/src/main/java/io/jmix/graphql/schema/permission/PermissionConfig.java, graphql/src/main/java/io/jmix/graphql/security/SpecificPermissionInstrumentation.java, graphql/src/test/groovy/io/jmix/graphql/AbstractGraphQLTest.groovy, graphql/src/test/groovy/io/jmix/graphql/datafetcher/PermissionsTest.groovy, graphql/src/test/groovy/io/jmix/graphql/datafetcher/SecurityTest.groovy, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/query-permissions.gql, graphql/src/test/resources/io/jmix/graphql/liquibase/security.sql
Specific permissions were added to the permissions query with tests
=> Support specific permissions in permissions query #114

graphql/src/main/java/io/jmix/graphql/datafetcher/EntityMutationDataFetcher.java, graphql/src/main/java/io/jmix/graphql/datafetcher/GqlEntityValidationException.java, graphql/src/test/groovy/io/jmix/graphql/AbstractGraphQLTest.groovy, graphql/src/test/groovy/io/jmix/graphql/datafetcher/MutationValidationTest.groovy, graphql/src/test/java/test_support/entity/test/CompositionO2OTestEntity.java, graphql/src/test/java/test_support/entity/test/DeeplyNestedTestEntity.java, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/upsert-datatypesTestEntity-bean-validation-more-dept.gql, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/upsert-datatypesTestEntity-bean-validation.gql, graphql/src/test/resources/io/jmix/graphql/messages.properties
Showing of parent attribute for composite bean validation has been implemented
=> Bean validation: Compositions #116

graphql/src/test/groovy/io/jmix/graphql/AbstractGraphQLTest.groovy, graphql/src/test/groovy/io/jmix/graphql/datafetcher/MutationValidationTest.groovy, graphql/src/test/resources/io/jmix/graphql/messages.properties, graphql/src/test/resources/io/jmix/graphql/messages_ru.properties
Tests for "Accept-Language" header have been implemented
=> Bean validation error messages should be localized depending on Accept-Language #115

README.md, graphql/src/main/java/io/jmix/graphql/datafetcher/EntityQueryDataFetcher.java, graphql/src/main/java/io/jmix/graphql/schema/GenericSchemaGenerator.java, graphql/src/test/groovy/io/jmix/graphql/datafetcher/FilterIntegrationTest.groovy, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/query-garage-count-with-filter.graphql, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/query-garage-count.graphql, graphql/src/test/resources/graphql/io/jmix/graphql/schema.graphql
Filter was added to count query
=> Add filter to count query #37

graphql/src/main/java/io/jmix/graphql/datafetcher/GqlEntityValidationException.java, graphql/src/test/groovy/io/jmix/graphql/datafetcher/MutationValidationTest.groovy
=> Bean validation: incorrect field path #132

graphql/src/main/java/io/jmix/graphql/InstrumentationUtils.java, graphql/src/main/java/io/jmix/graphql/limitation/JmixMaxQueryDepthInstrumentation.java, graphql/src/main/java/io/jmix/graphql/security/SpecificPermissionInstrumentation.java
=> Revert "protect introspection query with security"

README.md, graphql/src/main/java/io/jmix/graphql/datafetcher/EntityMutationDataFetcher.java, graphql/src/main/java/io/jmix/graphql/datafetcher/GqlEntityValidationException.java, graphql/src/main/java/io/jmix/graphql/schema/BaseTypesGenerator.java, graphql/src/test/groovy/io/jmix/graphql/datafetcher/MutationTest.groovy, graphql/src/test/groovy/io/jmix/graphql/datafetcher/MutationValidationTest.groovy, graphql/src/test/groovy/io/jmix/graphql/datafetcher/PermissionsTest.groovy, graphql/src/test/groovy/io/jmix/graphql/datafetcher/PopulateAndCheckCompositionTest.groovy, graphql/src/test/java/test_support/entity/test/DeeplyNestedTestEntity.java, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/upsert-datatypesTestEntity-composition.gql, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/upsert-datatypesTestEntity-deeply-nested-composition.gql, graphql/src/test/resources/graphql/io/jmix/graphql/schema.graphql, graphql/src/test/resources/io/jmix/graphql/liquibase/security.sql
Checking of composite attributes has been implemented
=> O2M Composition: Unexpected behavior when reverse attribute does not contain correct parent entity #104

graphql/src/main/java/io/jmix/graphql/datafetcher/EntityMutationDataFetcher.java, graphql/src/main/java/io/jmix/graphql/datafetcher/EntityQueryDataFetcher.java, graphql/src/main/java/io/jmix/graphql/service/IdentifierService.java
Added support of others id types in Data Fetchers
Now you can use id with Long, String, Integer, UUID types
=> Added support of others id types

graphql/graphql.gradle, graphql/src/main/java/io/jmix/graphql/controller/GraphQLFilesUploadController.java
Fix problems with complex variable path, like variables.testingEntity.picture in part of request "map"
=> Fix problems with complex variable path, like variables.testingEntity.picture

graphql/src/main/java/io/jmix/graphql/datafetcher/EntityMutationDataFetcher.java
Fix of issue https://github.com/Haulmont/jmix-graphql/issues/199
=> Fix incorrect logic on check composition relation

graphql/src/main/java/io/jmix/graphql/GraphQLConfiguration.java, graphql/src/main/java/io/jmix/graphql/GraphQlProperties.java, graphql/src/main/java/io/jmix/graphql/schema/FilterTypesGenerator.java, graphql/src/main/java/io/jmix/graphql/schema/GenericSchemaGenerator.java, graphql/src/test/groovy/io/jmix/graphql/SchemaMultipleSortGeneratedTest.groovy, graphql/src/test/groovy/io/jmix/graphql/datafetcher/sort/MultipleSortingTest.groovy, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/multiple-sort/cars-with-sort.gql, graphql/src/test/resources/graphql/io/jmix/graphql/datafetcher/multiple-sort/garages-with-sort.gql, graphql/src/test/resources/graphql/io/jmix/graphql/schema-multiple-sort.graphql, jmix-studio.xml
Provides property `io.jmix.graphql.multiple-sort-supported` to allow multiple Sort by conditions
=> Configurable multiple sort order
